# Header
menu:
  首页: /
  归档: /archives


# SubNav
subnav:
  github: "https://github.com/Mike-bel"
  weibo: "http://weibo.com/3137408085/profile?topnav=1&wvr=6&is_all=1"
  # rss: "#"
  # zhihu: "#"
  #douban: "#"
  #mail: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: 'UA-83125745-1'
favicon: /favicon.png

#你的头像url
avatar: /assets/imgSite/avatar.png
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: yifengzone
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  郭霖: http://blog.csdn.net/guolin_blog
  鸿洋: http://blog.csdn.net/lmj623565791
  任玉刚: http://blog.csdn.net/singwhatiwanna
  泡在网上的日子: http://www.jcodecraeer.com/plus/list.php?tid=16
  

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 长期拼搏在一线开发的安卓程序猿一枚，热衷于技术，沉浸于段子，微信公众号：技术鸟（微信号：NiaoTech）。If you can't fly then run, can't run then walk, can't walk then crawl, keep moving forward.
